name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies for API Gateway
      run: |
        cd api-gateway
        npm install

    - name: Install Dependencies for Post Service
      run: |
        cd post-service
        npm install

    - name: Install Dependencies for Comment Service
      run: |
        cd comment-service
        npm install
        
    - name: List Directory Contents
      run: |
        echo "Root directory contents:"
        ls -R    

    - name: Run Services
      env:
        COMMENT_SERVICE_DB_URL: ${{ secrets.COMMENT_SERVICE_DB_URL }}
        COMMENT_SERVICE_PORT: ${{ secrets.COMMENT_SERVICE_PORT }}
        POST_SERVICE_HOST: ${{ secrets.POST_SERVICE_HOST }}
        POST_SERVICE_DB_URL: ${{ secrets.POST_SERVICE_DB_URL }}
        POST_SERVICE_PORT: ${{ secrets.POST_SERVICE_PORT }}
      run: |
        # Start all services
        cd api-gateway && npm run start &
        cd ../post-service && npm run start &
        cd ../comment-service && npm run start &
        wait

    # (Optional) Add Deployment Step
    # For example: Deploy to Render, Heroku, or a cloud server.
